apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - image: php:8.2-fpm
        name: php
        ports:
          - containerPort: 9000
            name: php
        volumeMounts:
          - name: site
            mountPath: /var/www/html
      volumes:
        - name: site
          hostPath:
            path: /data/site
            type: Directory
