apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: www
  name: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - image: nginx:1.26
        name: nginx
        volumeMounts:
          - name: site
            mountPath: /usr/share/nginx/html
            readOnly: true
      volumes:
        - name: site
          hostPath:
            path: /data/site
            type: Directory
