---
name: lemp
services:
  web:
    image: nginx:${NGINX_IMAGE_TAG:-1.23}
    container_name: http
    hostname: srvweb
    volumes:
      - type: bind
        source: ../../site
        target: /usr/share/nginx/html
        bind:
          create_host_path: false
      - type: bind
        source: ../../nginx-conf
        target: /etc/nginx/conf.d
    ports:
      - ${NGINX_EXTERNAL_PORT}:80
    networks:
      stagenet:
        ipv4_address: ${STAGENET_PREFIX}.${NGINX_IPV4}
  php:
    image: php:${PHP_IMAGE_TAG}
    container_name: php
    hostname: php
    volumes:
      - type: bind
        source: ../../site
        target: /var/www/html
        bind:
          create_host_path: false
    networks:
      stagenet:
        ipv4_address: ${STAGENET_PREFIX}.${PHP_IPV4}
  db:
    image: mariadb:${MARIADB_IMAGE_TAG}
    container_name: mariadb
    hostname: mariadb
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - datadir:/var/lib/mysql
    networks:
      stagenet:
        ipv4_address: ${STAGENET_PREFIX}.${MARIADB_IPV4}
    environment:
      MARIADB_ROOT_PASSWORD: azerty
      MARIADB_DATABASE: stage

volumes:
  datadir:

networks:
  stagenet:
    ipam:
      config:
        - subnet: ${STAGENET_PREFIX}.0.0/16
    driver_opts:
      com.docker.network.bridge.name: stagenet0
